name: eslint
on: [push]
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
      - uses: actions/checkout@v3
      - name: Install node.js
      - uses: actions/setup-node@v3
        with:
          node-version: 16.14.2
      - run: yarn install
      - name: Lint source code with ESLint
      - run: yarn lint
